### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by jimparis** [XenGi/miniftx#6]
Hi,
I'm glad to see you using the MicroFTX design!  Adding activity LEDs is a great idea.  However, I'd like to request that you please change the name to avoid confusion with my original.  The CC-BY-SA license of the original work covers the design, but not the name.  I'd be happy to help suggest some alternate names if you'd like -- just let me know!
Thanks,
Jim

**Comment by XenGi** [comment]
I'm still thinking about something else. I really like µFTX but thats already taken by you. If you have some cool ideas, let me know.
Thx for the design btw having something that small is pretty awesome. :)

**Comment by XenGi** [comment]
Temporary name is MiniFTX now. I will change it to something completely different in he next version.
